apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml
- servicemonitor.yaml
- prometheusrules.yaml

images:
- name: ghcr.io/web3-frozen/onchain-monitor
  newName: ghcr.io/web3-frozen/onchain-monitor
  newTag: d1a79ab
- name: ghcr.io/web3-frozen/onchain-monitor-frontend
  newName: ghcr.io/web3-frozen/onchain-monitor-frontend
  newTag: 9f616ec
