apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml
- external-secret.yaml

images:
- name: ghcr.io/web3-frozen/demo-api
  newName: ghcr.io/web3-frozen/demo-api
  newTag: 07ac9e4
- name: ghcr.io/web3-frozen/demo-frontend
  newName: ghcr.io/web3-frozen/demo-frontend
  newTag: b75cc2a
