apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

images:
  - name: ghcr.io/web3-frozen/demo-api
    newTag: "13e9df9"
  - name: ghcr.io/web3-frozen/demo-frontend
    newTag: "295b6ba"
